# Generated by Django 3.1.2 on 2020-10-28 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.class')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.teacher')),
            ],
            options={
                'unique_together': {('course', 'class_id', 'teacher')},
            },
        ),
    ]
