# Generated by Django 3.1.2 on 2020-10-30 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20201030_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examname', models.CharField(max_length=20)),
                ('status', models.CharField(default='0', max_length=10)),
                ('ass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.assign')),
            ],
        ),
        migrations.RemoveField(
            model_name='marksclass',
            name='assign',
        ),
        migrations.DeleteModel(
            name='EnterMarks',
        ),
        migrations.DeleteModel(
            name='MarksClass',
        ),
    ]
