# Generated by Django 3.1.2 on 2020-10-30 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20201030_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarksConfirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examname', models.CharField(max_length=20)),
                ('status', models.BooleanField(default='True')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.course')),
                ('marks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.marks')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.student')),
            ],
        ),
    ]
