# Generated by Django 3.1.2 on 2020-11-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_marksconfirm_marksnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksconfirm',
            name='att',
            field=models.BooleanField(default='True'),
        ),
        migrations.AlterField(
            model_name='marksconfirm',
            name='status',
            field=models.CharField(default='not marked', max_length=20),
        ),
    ]
