# Generated by Django 3.1.2 on 2020-11-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_getmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='USNid',
            field=models.CharField(default=models.CharField(max_length=50, primary_key=True, serialize=False), max_length=50),
        ),
    ]
