# Generated by Django 3.1.2 on 2020-11-04 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_student_usnid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='USNid',
        ),
    ]
